CREATE TABLE `SYS_CHANNEL`
(
    `CHANNEL_ID`        int(11)      NOT NULL,
    `CODE`              varchar(64)                                       DEFAULT NULL,
    `NAME`              varchar(80)  NOT NULL,
    `AGGREGATOR`        int(11)      NOT NULL,
    `PROVIDER_CLASS`    char(255) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
    `LABEL`             tinyint(1)                                        DEFAULT '1',
    `SCAN`              tinyint(1)                                        DEFAULT '1',
    `LINE_HAUL`         tinyint(1)                                        DEFAULT '1',
    `CUSTOMS`           tinyint(1)                                        DEFAULT '1',
    `LABEL_TYPE`        int(11)      NOT NULL,
    `RESEND_CHANNEL`    int(11)      NOT NULL                             DEFAULT '0',
    `RETURN_ADDRESS`    char(27) CHARACTER SET latin1 COLLATE latin1_bin  DEFAULT NULL,
    `DESCRIPTION`       varchar(255) NOT NULL,
    `DESTINATION`       varchar(255)                                      DEFAULT NULL,
    `LEVEL`             int(11)                                           DEFAULT '0',
    `ORIGIN`            varchar(255)                                      DEFAULT '',
    `RETURN_CHANNEL`    int(11)      NOT NULL,
    `CONFIGURED_TITLE`  varchar(255)                                      DEFAULT NULL,
    `CONFIGURED_URL`    varchar(255)                                      DEFAULT NULL,
    `PROVIDED_TITLE`    varchar(255)                                      DEFAULT NULL,
    `PROVIDED_URL`      varchar(255)                                      DEFAULT NULL,
    `PROVISIONED_TITLE` varchar(255)                                      DEFAULT NULL,
    `PROVISIONED_URL`   varchar(255)                                      DEFAULT NULL,
    `CHANNEL_GROUP`     varchar(64)                                       DEFAULT NULL,
    `BIZ_TYPE`          int(11)                                           DEFAULT '1',
    `ACTIVE`            int(1)                                            DEFAULT '1',
    `WHITE_LABEL`       int(1)                                            DEFAULT '0',
    `WHITE_LABEL_TYPE`  int(11)                                           DEFAULT '0',
    `REMARK`            varchar(256)                                      DEFAULT NULL,
    PRIMARY KEY (`CHANNEL_ID`),
    KEY `IDX_SYS_CHANNEL_CHANNEL_ID` (`CHANNEL_ID`),
    KEY `IDX_SYS_CHANNEL_CODE` (`CODE`),
    KEY `IDX_SYS_CHANNEL_AGGREGATOR` (`AGGREGATOR`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8;