spring:
    jpa:
        database-platform: org.hibernate.dialect.MySQL5Dialect
    datasource:
        master:
            driverClassName: com.mysql.jdbc.Driver
            url: 'jdbc:mysql://127.0.0.1:3306/master?autoReconnect=true'
            username: 'root'
            password: '0001'
            type: com.alibaba.druid.pool.DruidDataSource
            druid:
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                filters: stat,wall,slf4j
                initialSize: 5
                maxActive: 20
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 5
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                asyncInit: true
                poolPreparedStatements: true
                timeBetweenEvictionRunsMillis: 60000
                maxOpenPreparedStatements: 20
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM sys_property
                dialect: org.hibernate.dialect.MySQL57Dialect
        slave:
            driverClassName: com.mysql.jdbc.Driver
            url: 'jdbc:mysql://127.0.0.1:3306/slave?autoReconnect=true'
            username: 'root'
            password: '0001'
            type: com.alibaba.druid.pool.DruidDataSource
            druid:
                connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
                filters: stat
                initialSize: 1
                maxActive: 20
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                asyncInit: true
                poolPreparedStatements: true
                timeBetweenEvictionRunsMillis: 60000
                maxOpenPreparedStatements: 20
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM sys_property
                dialect: org.hibernate.dialect.MySQL57Dialect
